###
POST http://localhost:3000/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "nombre" : "Alvaro",
    "apellido": "Vargas",
    "usuario" : "tryhard",
    "email": "Alvaro_mz@gmail.com",
    "password": "almohada",
    "pokefavoritos": "meawtho"
}

###
GET http://localhost:3000/api/usuarios HTTP/1.1

###
GET http://localhost:3000/api/usuarios/tortuga HTTP/1.1

###
GET http://localhost:3000/api/usuarios/63a3b2408d0138ba81971f49 HTTP/1.1
# GET http://localhost:3000/api/usuarios/63a32ce206b1acd6062e4436 HTTP/1.1

###
PUT http://localhost:3000/api/usuarios/63a32a9a06b1acd6062e4434 HTTP/1.1
Content-Type: application/json

{
    
    "nombre" : "luisito2",
    "apellido": "comunica",
    "usuario" : "tortuga",
    "email": "Alvaro_mz@gmail.com",
    "password": "mipapicr7",
    "pokefavoritos": "meawtho"
}

###
GET http://localhost:3000/api/usuarios HTTP/1.1

###
GET http://localhost:3000/api/usuarios/63a231c6bc21e97d1b6747e3 HTTP/1.1

###
PUT http://localhost:3000/api/usuarios/63a32a9a06b1acd6062e4434 HTTP/1.1
Content-Type: application/json

{
    "nombre" : "luisito3",
    "apellido": "comunica1",
    "usuario" : "tortuga1",
    "email": "Alvaro_mz1@gmail.com",
    "password": "mipapicr71",
    "pokefavoritos": "meawtho1"
}

###
DELETE http://localhost:3000/api/usuarios/639cd9f5faab81c61d2f0f8b HTTP/1.1